# Alembic Configuration File
# Relative to the location of the script

sqlalchemy.url = sqlite:///./test.db

# Logging configuration
loggers = {}
qualname_handlers = {}

# Logging level for 'sqlalchemy.engine'
sqlalchemy_log_level = WARNING
